/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hw10 */

#ifndef _Included_hw10
#define _Included_hw10
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hw10
 * Method:    convertFtoC
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_hw10_convertFtoC
  (JNIEnv *, jobject, jint);

/*
 * Class:     hw10
 * Method:    roundUp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_hw10_roundUp
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
